workflows:
  build-android:
    name: Asteroids
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    caching:
      paths:
        - ~/.gradle
        - ~/.pub-cache
